state <- read.csv(file = "C:/Users/MINGYEONG/Desktop/2020_KOR/ADP/R/Data_psds/state.csv")
mean(state[["Population"]])
mean(state[["Population"]], trim = 0.1)
median(state[["Population"]])
weighted.mean(state[["Murder.Rate"]], w=state[["Population"]])
library("matrixStats")
weightedMedian(state[["Murder.Rate"]], w=state[["Population"]])
